import type { Belt } from "@/types/content";

/**
 * The 7 tracks, themed as Mission Control clearance ranks.
 * moduleIds are filled from the module registry order (see content/index.ts),
 * but we also pin the canonical order here for the map.
 */
export const BELTS: Belt[] = [
  {
    id: "foundations",
    code: "0",
    rank: "Cadet",
    name: "Foundations",
    blurb: "How big is big, how fast is fast — the mental models everything stands on.",
    color: "#6bf0c8",
    moduleIds: [
      "what-is-system-design",
      "latency-numbers",
      "back-of-envelope",
      "latency-throughput-bandwidth",
      "vertical-horizontal-scaling",
      "request-lifecycle",
      "concurrency-parallelism",
      "scalability-laws",
    ],
  },
  {
    id: "building-blocks",
    code: "1",
    rank: "Ensign",
    name: "Building Blocks",
    blurb: "The Lego bricks of every real system: networking, balancers, caches, CDNs.",
    color: "#5eb0ff",
    moduleIds: [
      "dns-tcp-udp",
      "http-tls",
      "load-balancers",
      "caching-layers",
      "cache-strategies",
      "cache-eviction",
      "reverse-proxy-gateway",
      "cdn-edge",
      "serialization-formats",
      "connection-pooling",
    ],
  },
  {
    id: "data-at-scale",
    code: "2",
    rank: "Lieutenant",
    name: "Data at Scale",
    blurb: "Where most designs live or die — replication, sharding, consistency, consensus.",
    color: "#b79bff",
    moduleIds: [
      "sql-vs-nosql",
      "indexing-btree-lsm",
      "replication",
      "partitioning-sharding",
      "consistent-hashing",
      "cap-pacelc",
      "consistency-models",
      "acid-base-transactions",
      "2pc-vs-saga",
      "quorums",
      "distributed-ids",
      "oltp-vs-olap",
      "write-ahead-log",
      "mvcc",
      "change-data-capture",
      "object-storage",
      "search-inverted-index",
      "time-series-databases",
      "graph-databases",
    ],
  },
  {
    id: "reliability",
    code: "3",
    rank: "Commander",
    name: "Reliability & Robustness",
    blurb: "Designing for the day everything goes wrong — because it will.",
    color: "#ffcf6e",
    moduleIds: [
      "availability-nines-slo",
      "redundancy-failover",
      "rate-limiting",
      "circuit-breaker-bulkhead",
      "retries-backoff-idempotency",
      "backpressure",
      "observability",
      "chaos-engineering",
      "disaster-recovery",
      "deployment-strategies",
      "load-shedding-timeouts",
      "dead-letter-queues",
      "graceful-degradation",
    ],
  },
  {
    id: "patterns",
    code: "4",
    rank: "Captain",
    name: "Architecture Patterns",
    blurb: "Assembling the bricks into shapes with names.",
    color: "#ff9ec4",
    moduleIds: [
      "monolith-microservices",
      "api-styles",
      "realtime-websockets-sse",
      "message-queues-pubsub",
      "event-driven",
      "cqrs-event-sourcing",
      "serverless",
      "service-mesh",
      "batch-vs-stream",
      "strangler-fig",
      "outbox-pattern",
      "ddd-bounded-contexts",
      "bff-pattern",
      "api-versioning",
    ],
  },
  {
    id: "case-studies",
    code: "5",
    rank: "Flight Director",
    name: "Case Studies",
    blurb: "Put it together. Build real systems step by step, with trade-off checkpoints.",
    color: "#57e389",
    moduleIds: [
      "design-url-shortener",
      "design-rate-limiter",
      "design-news-feed",
      "design-chat",
      "design-video-streaming",
      "design-ride-sharing",
      "design-typeahead",
      "design-payments",
      "design-notifications",
      "design-job-scheduler",
      "design-web-crawler",
      "design-distributed-cache",
      "design-distributed-lock",
      "design-collaborative-editor",
      "design-message-queue",
      "design-leaderboard",
    ],
  },
  {
    id: "ai-systems",
    code: "6",
    rank: "Mission Commander",
    name: "AI / ML Systems",
    blurb: "The infrastructure behind modern AI — pipelines, serving, LLMs, agents.",
    color: "#ff6b8b",
    moduleIds: [
      "ml-lifecycle",
      "batch-vs-online-inference",
      "feature-stores",
      "training-pipelines",
      "model-serving-batching",
      "gpu-economics",
      "distributed-training",
      "vector-databases",
      "llm-serving",
      "rag-architecture",
      "recommendation-systems",
      "agentic-architectures",
      "model-routing-moe",
      "llm-guardrails-evals",
      "prompt-response-caching",
      "embeddings-tokenization",
      "model-monitoring-drift",
      "ab-testing-bandits",
      "fine-tuning-vs-rag",
      "mlops-cicd",
      "multimodal-systems",
    ],
  },
  {
    id: "algorithms",
    code: "7",
    rank: "Systems Architect",
    name: "Algorithms & Consensus",
    blurb: "The distributed-systems algorithms that power everything above.",
    color: "#5eead4",
    moduleIds: [
      "consensus-raft",
      "paxos-basics",
      "gossip-protocol",
      "logical-clocks",
      "crdts",
      "merkle-trees",
      "bloom-filters",
      "hyperloglog",
      "count-min-sketch",
      "skip-lists",
      "trie",
      "geospatial-index",
      "mapreduce",
      "chain-replication",
    ],
  },
  {
    id: "security",
    code: "8",
    rank: "Security Officer",
    name: "Security & Trust",
    blurb: "Authentication, authorization, encryption, and zero-trust design.",
    color: "#ff9e64",
    moduleIds: [
      "authentication",
      "oauth-oidc",
      "authorization-rbac",
      "encryption-rest-transit",
      "api-security-owasp",
      "secrets-management",
      "zero-trust-mtls",
    ],
  },
];

export const BELT_BY_ID = Object.fromEntries(BELTS.map((b) => [b.id, b]));
