import type { AlgorithmCard, GlossaryEntry } from "@/types/content";

/**
 * Algorithm & strategy deep-dive cards. Each `id` matches a real module so the
 * Algorithms page links straight to the interactive lesson.
 */
export const ALGORITHMS: AlgorithmCard[] = [
  {
    id: "consistent-hashing",
    name: "Consistent hashing",
    gist: "Place nodes + keys on a ring; adding/removing a node moves only ~1/N keys.",
    usedIn: "Distributed caches, Dynamo/Cassandra sharding, shard routers.",
    instrument: "NodeRing",
  },
  {
    id: "consensus-raft",
    name: "Raft / consensus",
    gist: "Elect a leader that orders all writes; commit once a majority replicates.",
    usedIn: "etcd, Consul, CockroachDB, schedulers, config stores.",
    instrument: "Timeline",
  },
  {
    id: "paxos-basics",
    name: "Paxos",
    gist: "Reach agreement on a value via prepare/accept with majority promises.",
    usedIn: "The foundation of fault-tolerant consensus (Chubby, Spanner).",
    instrument: "TradeoffLab",
  },
  {
    id: "gossip-protocol",
    name: "Gossip / epidemic",
    gist: "Each node shares state with random peers; info spreads in O(log N) rounds.",
    usedIn: "Membership/failure detection (SWIM), Cassandra, Consul.",
    instrument: "FlowStage",
  },
  {
    id: "logical-clocks",
    name: "Lamport & vector clocks",
    gist: "Order events by causality without a shared physical clock.",
    usedIn: "Conflict detection in leaderless/multi-leader systems, CRDTs.",
    instrument: "Timeline",
  },
  {
    id: "crdts",
    name: "CRDTs",
    gist: "Data types whose concurrent updates always merge to the same result.",
    usedIn: "Collaborative editors, offline-first apps, multi-leader stores.",
    instrument: "Timeline",
  },
  {
    id: "merkle-trees",
    name: "Merkle trees",
    gist: "A tree of hashes that finds differences between replicas in log time.",
    usedIn: "Anti-entropy repair, Git, blockchains, backups.",
    instrument: "FlowStage",
  },
  {
    id: "bloom-filters",
    name: "Bloom filter",
    gist: "A tiny probabilistic set: 'definitely not present' or 'maybe present'.",
    usedIn: "LSM-tree read skipping, caches, crawlers, dedup.",
    instrument: "BloomFilter",
  },
  {
    id: "hyperloglog",
    name: "HyperLogLog",
    gist: "Estimate the count of distinct items in kilobytes, within ~2%.",
    usedIn: "Unique-visitor counts, analytics, Redis PFCOUNT.",
    instrument: "TradeoffLab",
  },
  {
    id: "count-min-sketch",
    name: "Count-Min Sketch",
    gist: "Approximate item frequencies (heavy hitters) in fixed small memory.",
    usedIn: "Trending topics, traffic monitoring, anomaly detection.",
    instrument: "TradeoffLab",
  },
  {
    id: "skip-lists",
    name: "Skip lists",
    gist: "A layered linked list giving O(log n) search with easy concurrency.",
    usedIn: "Redis sorted sets, LSM memtables, leaderboards.",
    instrument: "FlowStage",
  },
  {
    id: "trie",
    name: "Trie (prefix tree)",
    gist: "Store strings by shared prefix for instant prefix/autocomplete queries.",
    usedIn: "Typeahead, IP routing (longest-prefix), dictionaries.",
    instrument: "FlowStage",
  },
  {
    id: "geospatial-index",
    name: "Geohash / quadtree",
    gist: "Encode 2D locations into keys/trees for fast 'near me' queries.",
    usedIn: "Ride-sharing, maps, delivery, proximity search.",
    instrument: "FlowStage",
  },
  {
    id: "mapreduce",
    name: "MapReduce / shuffle",
    gist: "Map data in parallel, shuffle by key, reduce to aggregate — at scale.",
    usedIn: "Hadoop, Spark, large-scale batch analytics.",
    instrument: "FlowStage",
  },
  {
    id: "chain-replication",
    name: "Chain replication",
    gist: "Writes flow head→tail; the tail commits and serves consistent reads.",
    usedIn: "Strongly-consistent storage systems (CRAQ, object stores).",
    instrument: "Timeline",
  },
  {
    id: "rate-limiting",
    name: "Token / leaky bucket",
    gist: "Tokens refill at a rate; each request spends one — caps rate, allows bursts.",
    usedIn: "Rate limiting, traffic shaping, API quotas.",
    instrument: "LoadDial",
  },
  {
    id: "cache-eviction",
    name: "LRU / LFU eviction",
    gist: "Decide what to drop from a full cache by recency or frequency.",
    usedIn: "Every cache: CPU, CDN, Redis, DB buffer pools.",
    instrument: "CacheGrid",
  },
  {
    id: "retries-backoff-idempotency",
    name: "Backoff + jitter",
    gist: "Grow retry delays and randomize them so clients don't retry in lockstep.",
    usedIn: "Every resilient client; prevents retry storms.",
    instrument: "Timeline",
  },
  {
    id: "vector-databases",
    name: "HNSW / ANN search",
    gist: "A navigable graph for logarithmic nearest-neighbor vector search.",
    usedIn: "Vector databases, semantic search, RAG retrieval.",
    instrument: "FlowStage",
  },
];

/** Searchable glossary — one-line definition + one analogy. */
export const GLOSSARY: GlossaryEntry[] = [
  { term: "Latency", definition: "Time for one operation to complete.", analogy: "How long your one letter takes to arrive." },
  { term: "Throughput", definition: "Operations completed per unit time.", analogy: "Letters the post office moves per day." },
  { term: "Availability", definition: "Fraction of time a system is operational.", analogy: "How often the shop is actually open." },
  { term: "Consistency", definition: "Whether all readers see the same, latest data.", analogy: "Everyone's calendar showing the same event time." },
  { term: "Consensus", definition: "Getting distributed nodes to agree on one value/order despite failures.", analogy: "A committee reaching a binding vote even if some members are absent." },
  { term: "Quorum", definition: "A minimum number of nodes that must agree (R+W>N).", analogy: "A committee needing enough members present to vote." },
  { term: "Partition (network)", definition: "A break splitting nodes so they can't communicate.", analogy: "Two rooms whose phone line is cut." },
  { term: "Replication", definition: "Keeping copies of data on multiple nodes.", analogy: "Photocopies of a document in several offices." },
  { term: "Sharding", definition: "Splitting data across nodes so each holds a slice.", analogy: "Splitting a phone book across many volumes." },
  { term: "Idempotency", definition: "Doing an operation twice has the same effect as once.", analogy: "Pressing an elevator button that's already lit." },
  { term: "Backpressure", definition: "Signalling upstream to slow down when overloaded.", analogy: "A 'lane closed' sign before the jam." },
  { term: "Eventual consistency", definition: "Replicas converge to the same value over time.", analogy: "A rumor that eventually reaches everyone accurately." },
  { term: "Hot shard / hotspot", definition: "One partition getting far more load than others.", analogy: "One checkout lane with the whole store's queue." },
  { term: "Cold start", definition: "First-request latency to initialize a new instance.", analogy: "Warming up a car engine on a cold morning." },
  { term: "Gossip protocol", definition: "Nodes spread state to random peers until all converge.", analogy: "Office gossip reaching everyone in a few hops." },
  { term: "Vector clock", definition: "Per-node counters that capture causality and detect concurrency.", analogy: "Numbering emails so replies always follow what they answer." },
  { term: "CRDT", definition: "A data type whose concurrent edits always merge to the same result.", analogy: "Two shopping lists that combine to the same final list in any order." },
  { term: "Bloom filter", definition: "A probabilistic set: 'definitely no' or 'probably yes' in tiny space.", analogy: "A quick stamp check: missing stamp = definitely not on the list." },
  { term: "Write-ahead log (WAL)", definition: "Record changes to a durable log before applying them.", analogy: "Writing your intent in ink before acting, so it can be finished after a faint." },
  { term: "MVCC", definition: "Keep multiple row versions so readers don't block writers.", analogy: "Reading the doc version you opened while someone saves a new one." },
  { term: "CDC", definition: "Stream a database's row changes to other systems in real time.", analogy: "A newswire broadcasting every official change from one source." },
  { term: "Idempotency key", definition: "A token that makes a repeated request apply only once.", analogy: "A ticket number: hand it in twice, still one entry." },
  { term: "KV cache (LLM)", definition: "Stored attention keys/values so tokens aren't recomputed.", analogy: "Keeping your notes so you don't re-read the whole book." },
  { term: "Embedding", definition: "A vector representing meaning, for similarity search.", analogy: "GPS coordinates for concepts." },
  { term: "Token (LLM)", definition: "The ~4-character unit LLMs process and bill by.", analogy: "The LEGO bricks that text is broken into." },
  { term: "Drift", definition: "A deployed model degrading as the world changes.", analogy: "A city map going out of date as roads change." },
  { term: "Canary deploy", definition: "Send a small % of traffic to a new version before full rollout.", analogy: "A canary in a coal mine — expose a few first." },
  { term: "OAuth 2.0", definition: "Delegated, scoped access to your data without sharing your password.", analogy: "A hotel key card, not your house keys." },
  { term: "JWT", definition: "A signed token carrying claims the server can verify statelessly.", analogy: "A tamper-proof wristband that works until it expires." },
  { term: "RBAC", definition: "Grant permissions via roles (admin, editor).", analogy: "A job title that unlocks certain doors." },
  { term: "Zero trust", definition: "Trust nothing by network location; verify every request.", analogy: "Every office door needs a badge, not just the front entrance." },
  { term: "Inverted index", definition: "Maps each term to the documents containing it, for fast search.", analogy: "The index at the back of a textbook." },
  { term: "SLO / SLA / SLI", definition: "Target / contract / measured indicator of reliability.", analogy: "Goal, promise, and speedometer for uptime." },
];
